## ------------------------------------------------------------
## Sidebar Nav Configuration
## This document contains configuration for the sidebar
##
## ------------------------------------------------------------

articles:

## ------------------------------------------------------------
## Getting Started
## ------------------------------------------------------------

  - title: Getting Started
    url: /getting-started
    children:

      - title: Dashboard Overview
        url: /getting-started/dashboard-overview

      - title: Create a Tenant
        url: /getting-started/create-tenant
      
      - title: Set Up An App
        url: /getting-started/set-up-app
        children:

          - title: Regular Web App
            url: /getting-started/set-up-app/regular-web

          - title: Native App
            url: /getting-started/set-up-app/native

          - title: Single-Page App
            url: /getting-started/set-up-app/spa

          - title: Backend/Service
            url: /getting-started/set-up-app/m2m

      - title: Set Up an API
        url: /getting-started/set-up-api
        children:

          - title: Set Up Multiple Environments
            url: /getting-started/setting-up-env
            hidden: true

## ------------------------------------------------------------
## Login
## ------------------------------------------------------------

  # - title: Login
  #   url: /login
  #   children:

  #     - title:
  #       url:

## ------------------------------------------------------------
## Identity Providers / Connections
## ------------------------------------------------------------

  - title: Connections (Identity Providers)
    url: /connections
    children:

      - title: Social Identity Providers
        url: /identityproviders#social

      - title: Enterprise Identity Providers
        url: /identityproviders#enterprise

      - title: Legal Identity Providers
        url: /identityproviders#legal
      
      - title: Database
        url: /connections/database
        children:

          - title: Auth0 User Store
            url: /database#using-the-auth0-user-store

          - title: Your Database
            url: /database/custom-db

      - title: SAML Identity Providers
        url: /connections/saml

      - title: Passwordless Authentication
        url: /connections/passwordless
        children:

          - title: Native Passwordless
            url: /connections/passwordless/native-passwordless-universal

          - title: Using Email
            url: /connections/passwordless/email

          - title: Using SMS
            url: /connections/passwordless/sms

          - title: FAQ
            url: /connections/passwordless/faq

      - title: Pass Parameters to Identity Providers
        url: /connections/pass-parameters-to-idps

## ------------------------------------------------------------
## Authorization
## ------------------------------------------------------------

  - title: Authorization
    url: /authorization
    children:
      
      - title: Authorization Flows
        url: /authorization/flows
        children:

          - title: Authorization Code
            url: /flows/guides/auth-code/call-api-auth-code

          - title: Authorization Code with PKCE
            url: /flows/guides/auth-code-pkce/call-api-auth-code-pkce

          - title: Client Credentials
            url: /flows/guides/client-credentials/call-api-client-credentials

          - title: Implicit
            url: /flows/guides/implicit/call-api-implicit
            children: 
              - title: Mitigate Replay Attacks
                url: /flows/mitigate-replay-attacks
      
      - title: Core Role-based Access Control
        url: /authorization/concepts/rbac
        children:
          - title: Getting Started
            url: /authorization/guides/how-to

          - title: Manage Roles
            url: /authorization/guides/manage-roles

          - title: Manage RBAC Users
            url: /authorization/guides/manage-users

          - title: Manage RBAC Permissions
            url: /authorization/guides/manage-permissions

            # TODO: Also in Configuration. Should probably be here instead
          - title: Enable RBAC for APIs
            url: /dashboard/guides/apis/enable-rbac

      - title: Authorization Extension
        url: /extensions/authorization-extension

      - title: Core vs. Extension
        url: /authorization/concepts/core-vs-extension

## ------------------------------------------------------------
## CONFIGURATION
## ------------------------------------------------------------
  - title: Configuration
    url: /configure
    children:

      - title: Tenant Configuration
        url: /configure/tenants
        children:

          - title: Tenant Settings
            url: /configure/tenants/settings

          - title: Manage Tenant Administrators
            url: /configure/tenants/manage-dashboard-admins

          - title: Configure Session Lifetime Settings
            url: /configure/tenants/session-lifetime

          - title: Enable SSO for Tenants
            url: /configure/tenants/enable-sso

          - title: Configure Device User Code Settings
            url: /configure/tenants/device-user-code-settings

          - title: Recommended Settings
            url: /configure/tenants/recommended-settings

          - title: Create Multiple Tenants
            url: /configure/tenants/create-multiple-tenants
            hidden: true

      - title: Application Configuration
        url: /configure/applications
        children:

          - title: Application Settings
            url: /configure/applications/settings

          - title: Enable SSO for Applications
            url: /configure/applications/enable-sso

          - title: Update Grant Types
            url: /configure/applications/update-grant-types

          - title: Android App Links
            url: /configure/applications/enable-android-app-links

          - title: Apple Universal Links
            url: /configure/applications/enable-universal-links

          - title: Set Up Add-ons
            url: /configure/applications/set-up-addons

          - title: Remove Applications
            url: /configure/applications/remove-app

          - title: Check App Type
            url: /configure/applications/view-app-type-confidential-public

          - title: Rotate Client Secret
            url: /configure/applications/rotate-client-secret

          - title: Recommended Settings
            url: /configure/applications/recommended-settings

          - title: View Add-ons
            url: /configure/applications/view-addons
            hidden: true

      - title: API Configuration
        url: /configure/apis
        children:

          - title: API Settings
            url: /configure/apis/settings

          - title: Signing Algorithms
            url: /configure/apis/signing-algorithms

          - title: Represent Multiple APIs with a Single API
            url: /configure/apis/represent-multiple-apis

          - title: Enable Role-Based Access Control for APIs
            url: /configure/apis/enable-rbac

          - title: Add Permissions
            url: /configure/apis/add-permissions

          - title: Delete Permissions
            url: /configure/apis/delete-permissions

          - title: Dashboard Views for APIs
            url: /configure/apis/views-apis

      - title: Single Sign-On
        url: /configure/sso
        children:

          - title: Single Sign-On with Auth0
            url: /configure/sso/sso-auth0

      - title: Anomaly Detection
        url: /configure/anomaly-detection
        children:

          - title: Breached Password Security
            url: /configure/anomaly-detection/breached-passwords

          - title: Set Preferences
            url: /configure/anomaly-detection/set-preferences

          - title: Customize Emails
            url: /configure/anomaly-detection/customize-blocked-account-emails

          - title: Restrictions and Limitations
            url: /configure/anomaly-detection/restrictions-limitations

          - title: FAQs
            url: /configure/anomaly-detection/faqs

          - title: Enable and Disable Brute Force Protection
            url: /configure/anomaly-detection/enable-disable-brute-force-protection
            hidden: true

          - title: Breached Password Detection Triggers
            url: /configure/anomaly-detection/breached-password-detection-triggers-actions
            hidden: true

          - title: Brute-Force Protection Triggers
            url: /configure/anomaly-detection/brute-force-protection-triggers-actions
            hidden: true

      - title: SAML Configuration
        url: /configure/saml
        children:

          - title: Overview
            url: /configure/saml/overview

          - title: Configure Auth0 as a Service Provider
            url: /configure/saml/auth0-as-service-provider

          - title: Configure Auth0 as an Identity Provider
            url: /configure/saml/auth0-as-identity-provider

          - title: Configure Auth0 as Both Service and Identity Provider
            url: /configure/saml/auth0-as-identity-and-service-provider

          - title: SAML Design Considerations
            url: /configure/saml/design-considerations

          - title: Supported SAML Options and Bindings
            url: /configure/saml/supported-options-and-bindings

          - title: Customize SAML Assertions
            url: /configure/saml/saml-assertions

          - title: Logout
            url: /configure/saml/logout

          - title: Deprovision Users
            url: /configure/saml/deprovision-users

          - title: Logout
            url: /configure/saml/logout
            
          - title: SAML Configurations for SSO Integrations
            url: /configure/saml/sso-integrations

          - title: Special SAML Configuration Scenarios
            url: /configure/saml/special-scenarios
            children:

              - title: IdP-Initiated Single Sign-On
                url: /configure/saml/special-scenarios/idp-initiated-sso
                hidden: true

              - title: Signing and Encrypting SAML Requests
                url: /configure/saml/special-scenarios/signing-and-encrypting-saml-requests
                hidden: true

      - title: Whitelist IP Addresses
        url: /configure/ip-whitelist

## ------------------------------------------------------------
## Manage Users
## ------------------------------------------------------------

  - title: Manage Users
    url: /manage-users
    children:
      - title: Overview
        url: /manage-users/overview
        children:

        - title: User Profiles
          url: /manage-users/overview-user-profile
          hidden: true

        - title: Metadata
          url: /manage-users/overview-user-metadata
          hidden: true
      
      - title: Using the Dashboard
        url: /manage-users/manage-user-using-the-dashboard

      - title: Using the API
        url: /manage-users/manage-users-using-the-management-api
      
      - title: Link User Accounts
        url: /extend-integrate/extensions/account-link

      - title: Blacklist User Attributes
        url: /manage-users/blacklisting-attributes

      - title: Import & Export Users
        url: /manage-users/overview-user-migration
        children:

        - title: File Schema
          url: /manage-users/bulk-import-database-schema-examples

        - title: Automatic
          url: /manage-users/configure-automatic-migration

        - title: Bulk Import
          url: /manage-users/bulk-user-imports

        - title: Bulk Export
          url: /manage-users/bulk-user-exports

        - title: User Import/Export Extension
          url: /extend-integrate/extensions/user-import-export

        - title: Examples
          url: /manage-users/user-migration-scenarios

      - title: User Search
        url: /manage-users/search/v3
        children: 

        - title: Get Users
          url: /manage-users/serch/v3/get-users-endpoint

        - title: Get Users by Email
          url: /manage-users/serch/v3/get-users-by-email-endpoint

        - title: Get Users by ID
          url: /manage-users/serch/v3/get-users-by-ID-endpoint

        - title: Sort Results
          url: /manage-users/serch/v3/sort-search-results

        - title: Results Pagination
          url: /manage-users/serch/v3/view-search-results-by-page

        - title: Query Syntax
          url: /manage-users/serch/v3/query-syntax

## ------------------------------------------------------------
## Branding & Customization
## ------------------------------------------------------------

  - title: Branding & Customization
    url: /branding-customization
    children:
      - title: Custom Domains
        url: /branding-customization/custom-domains
        children:
          - title: Custom Domains with Self-Managed Certificates
            url: /branding-customization/custom-domains/self-managed-certificates
      
      - title: Login Pages
        url: /test
        children:
          - title: Universal Login - Advanced Customization
            url: /universal-login/advanced-customization

          - title: Signup
            url: /libraries/custom-signup

          - title: Customize Error Pages
            url: /universal-login/custom-error-pages

      - title: Email
        url: /branding-customization/email/templates
        children:
          - title: Email Template Syntax
            url: /branding-customization/email/liquid-syntax

          - title: Blocked Account Emails
            url: /anomaly-detection/guides/customize-blocked-account-emails
      
      - title: SMS Messages
        url: /multifactor-authentication/sms-templates

      - title: Consent Prompt
        url: /scopes/current/guides/customize-consent-prompt

      - title: Internationalization
        url: /branding-customization/i18n

## ------------------------------------------------------------
## Extend & Integrate
## ------------------------------------------------------------

  - title: Extend & Integrate
    url: /extend-integrate
    children:
      - title: Rules
        url: /extend-integrate/rules
      
      - title: Hooks
        url: /extend-integrate/hooks

      - title: Extensions
        url: /extend-integrate/extensions
      
      - title: Analytics Integrations
        url: /extend-integrate/integrations/analytics

      - title: Single Sign-On Integrations
        url: /extend-integrate/integrations/sso

      - title: Marketing Integrations
        url: /extend-integrate/integrations/marketing

      - title: Add-ons
        url: /extend-integrate/addons

## ------------------------------------------------------------
## Monitor
## ------------------------------------------------------------
  
  - title: Monitoring
    url: /monitor
    children:

      - title: Logs
        url: /monitor/logs
        children:

          - title: Query Syntax
            url: /monitor/logs/query-syntax

          - title: Migrate from Logs Search v2 to v3
            url: /monitor/logs/migrate-logs-v2-v3
            hidden: true

      - title: Check Auth0 Status
        url: /monitor/check-auth0-status

      - title: Check Supporting Services Status
        url: /monitor/check-supporting-services

      - title: Check External Services Status
        url: /monitor/check-external-services

      - title: Monitor Applications
        url: /monitor/applications

      - title: Monitor Using SCOM
        url: /monitor/scom

      - title: Monitoring the AD/LDAP Connector with System Center Operations Manager
        url: /monitor/scom-adldap-connector
        hidden: true

      - title: AD/LDAP Connector Health Monitor
        url: /extend-integrate/extensions/adldap-connector
        hidden: true

      - title: Send Events to Keen
        url: /monitor/send-events-to-keenio
        hidden: true

      - title: Send Events to Segment
        url: /monitor/send-events-to-segmentio
        hidden: true

      - title: Send Events to Splunk
        url: /monitor/send-events-to-splunk
        hidden: true

      - title: Track New Leads in Salesforce
        url: /monitor/track-leads-salesforce
        hidden: true

      - title: Track New Sign-ups in Salesforce
        url: /monitor/track-signups-salesforce
        hidden: true

## ------------------------------------------------------------
## Deploy
## ------------------------------------------------------------

  - title: Deploy
    url: /deploy
    children:
      - title: Deployment Options
        url: /deploy/deployment-models
      
      - title: Deploy Checklist
        url: /deploy/checklist

      - title: Pre-Deployment
        url: /deploy/pre-deployment
      
      - title: Deploy CLI Extension
        url: /deploy/deploy-cli

## ------------------------------------------------------------
## Troubleshooting
## ------------------------------------------------------------

  - title: Troubleshooting
    url: /troubleshoot
    children:
      - title: Basics
        url: /troubleshoot/basics
      
      - title: Common Authentication Errors
        url: /troubleshoot/error-messages
        children:
          - title: Standard Error Messages
            url: /api/authentication#standard-error-responses

      - title: Roles-Based Authorization
        url: /troubleshoot/rbac
        children:
          - title: Authorization Extension
            url: /troubleshoot/auth-extension
      
      - title: Multi-factor Authentication
        url: /troubleshoot/mfa

      - title: SAML
        url: /troubleshoot/saml
        children:
          - title: Common SAML Errors
            url: /troubleshoot/saml/common-saml-errors
          
          - title: Troubleshooting When Auth0 is the Service Provider
            url: /troubleshoot/saml/auth0-as-sp
          
          - title: Troubleshooting When Auth0 is the Identity Provider
            url: /troubleshoot/saml/auth0-as-idp

      - title: Deprecation Errors
        url: /troubleshoot/deprecation-errors

      - title: Issues with...
        url: /troubleshoot/issues

      - title: HTTP Archive (HAR) 
        url: /troubleshoot/har

      - title: Custom Databases
        url: /troubleshoot/custom-db

      - title: Deploy CLI
        url: /troubleshoot/deploy-cli

      - title: AD/LDAP Connector
        url: /troubleshoot/connector

## ------------------------------------------------------------
## About Auth0
## ------------------------------------------------------------

  - title: About Auth0
    url: /about-auth0
    children:
      - title: Overview
        url: /about-auth0/overview
      
      - title: The Basics
        url: /about-auth0/the-basics
      
      - title: Auth0 & Data Privacy
        url: /about-auth0/auth0-and-data-privacy

      - title: Change Log
        url: https://auth0.com/changelog

  - title: Auth0 Community
    url: https://community.auth0.com/

  - title: Auth0 Blog
    url: https://auth0.com/blog/