## ------------------------------------------------------------
## Sidebar Nav Configuration
## This document contains configuration for the sidebar
##
## ------------------------------------------------------------

articles:

## ------------------------------------------------------------
## Manage Users
## ------------------------------------------------------------

  - title: Manage Users
    url: "/guides-tutorials/manage-users"
    children:
      - title: Overview
        url: "/guides-tutorials/manage-users/overview"
        children:

        - title: User Profiles
          url: "/guides-tutorials/manage-users/overview-user-profile"
          hidden: true

        - title: Metadata
          url: "/guides-tutorials/manage-users/overview-user-metadata"
          hidden: true
      
      - title: Using the Dashboard
        url: "/guides-tutorials/manage-users/manage-user-using-the-dashboard"

      - title: Using the API
        url: "/guides-tutorials/manage-users/manage-users-using-the-management-api"
      
      - title: Link User Accounts
        url: "/guides-tutorials/extend-integrate/extensions/account-link"

      - title: Blacklist User Attributes
        url: "/guides-tutorials/manage-users/blacklisting-attributes"

      - title: Import & Export Users
        url: "/guides-tutorials/manage-users/overview-user-migration"
        children:

        - title: File Schema
          url: "/guides-tutorials/manage-users/bulk-import-database-schema-examples"

        - title: Automatic
          url: "/guides-tutorials/manage-users/configure-automatic-migration"

        - title: Bulk Import
          url: "/guides-tutorials/manage-users/bulk-user-imports"

        - title: Bulk Export
          url: "/guides-tutorials/manage-users/bulk-user-exports"

        - title: User Import/Export Extension
          url: "/guides-tutorials/extend-integrate/extensions/user-import-export"

        - title: Examples
          url: "/guides-tutorials/manage-users/user-migration-scenarios"

      - title: User Search
        url: "/guides-tutorials/manage-users/search/v3"
        children: 

        - title: Get Users
          url: "/guides-tutorials/manage-users/serch/v3/get-users-endpoint"

        - title: Get Users by Email
          url: "/guides-tutorials/manage-users/serch/v3/get-users-by-email-endpoint"

        - title: Get Users by ID
          url: "/guides-tutorials/manage-users/serch/v3/get-users-by-ID-endpoint"

        - title: Sort Results
          url: "/guides-tutorials/manage-users/serch/v3/sort-search-results"

        - title: Results Pagination
          url: "/guides-tutorials/manage-users/serch/v3/view-search-results-by-page"

        - title: Query Syntax
          url: "/guides-tutorials/manage-users/serch/v3/query-syntax"